apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-monitoring
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: default
  project: default
  source:
    path: charts/cluster-monitoring
    repoURL: https://github.com/rh-aiservices-bu/rh1-llmd-lab-2026
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
