apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: grafana
  project: default
  source:
    path: charts/grafana
    repoURL: https://github.com/rh-aiservices-bu/rh1-llmd-lab-2026
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
  ignoreDifferences:
    - kind: Secret
      name: grafana-proxy
      jsonPointers:
        - /data/session_secret
